name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Docker image
      run: docker build -t authentication-service:${{ github.sha }} .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com

    - name: Push Docker image to Amazon ECR
      run: |
        docker tag authentication-service:${{ github.sha }} <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/authentication-service:${{ github.sha }}
        docker push <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/authentication-service:${{ github.sha }}

    - name: Deploy to EKS with Terraform
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
